---
application:
  name: "seedtelebot"
  project: "SeedTelegram"
  organization: "QoveryCommunity"
  port: 8080
routers:
- name: "main-seedtelebot"
  routes:
  - application_name: "seedtelebot"
    paths:
    - "/*"
